### ISSUE TITLE
Error installing theme

### ISSUE THREAD

**Issue by StartZeroGnu** [StartZeroGnu/jekyll-szflex-theme#1]
@geraldb what am I doing wrong?

```
$ mrhyde new sz-flex

mrhyde/0.1.1 on Ruby 2.3.1 (2016-04-26) [i686-linux]
mrhyde/0.1.1 on Ruby 2.3.1 (2016-04-26) [i686-linux]
GET https://github.com/mrhydescripts/scripts/raw/master/sz-flex.rb
starting new MrHyde script (sitefile) {}; lets go
Welcome, before setting up your site Mr. Hyde will ask you some questions.
Q: What's your site's title? [Sz Flex Theme]: TestSite
Q: What's your name? [StartZeroGnu]: TestAuthor
Thanks! Ready-to-go. Stand back.
  handle install_theme SZ-Flex, {}
GET https://github.com/drjekyllthemes/themes/raw/master/themes.yml

*** error: *** theme 'sz-flex' not found; sorry
```

**Comment by geraldb** [comment]
@StartZeroGnu the answer copied from the pull request. Thanks for trying.

```
*** error: *** theme 'sz-flex' not found; sorry
```

I see. Change:

```
 install_theme "SZ-Flex"
```

to use your full github name e.g.:

```
 install_theme "StartZeroGnu/jekyll-szflex-theme"
```

Cheers.

**Comment by StartZeroGnu** [comment]
I would like to install the theme from "drjekyllthemes" I add the theme and repo data to "https://github.com/drjekyllthemes/themes/blob/master/themes.yml" but the theme does not appear in "http://drjekyllthemes.github.io/"

I used `install_theme "SZ-Flex"` which it is the name of the theme in "drjekyllthemes"

1- why the theme does not appear in "http://drjekyllthemes.github.io/"? (I did wrong?)
2- why not find the theme if in "https://github.com/drjekyllthemes/themes/blob/master/themes.yml" ? (I did wrong?)

thanks for your patience @geraldb

**Comment by geraldb** [comment]
> 2- why not find the theme if in "https://github.com/drjekyllthemes/themes/blob/master/themes.yml" ? (I did wrong?)

your theme is already included (thanks for the pull request) - it uses your theme title for the shortcut

> - title:     SZ-Flex (Blog)

try:

```
$ drjekyll list
```

and it should include your theme as the last entry with the generated key (urlified name from the title). Cheers. 

I'd say for Mr Hyde its easier (and safer) to use the full github name >StartZeroGnu/jekyll-szflex-theme<.  It's "internal" - the user does NOT have to type it out or something. Cheers.

**Comment by geraldb** [comment]
@StartZeroGnu Just browsing your repo - just wondering why are you using a branch for mrhyde e.g. mr-hyde?  e.g why not use the (same) master branch?  Any reason - difference?  The idea of mrhyde is to work with themes "out-of-the-box" - no need for a "custom" branch e.g. all scripting is in your ruby mrhyde starter wizard script. Cheers.

**Comment by StartZeroGnu** [comment]
The reason to use the mr-hyde branch is the _config.yml file, include $name$ and $title$ to setup author: and title:

p.s. the theme does not appear in "http://drjekyllthemes.github.io/"

![01](https://cloud.githubusercontent.com/assets/22280286/19978815/8270cb82-a1f8-11e6-9690-292bbcb88b80.png)

**Comment by StartZeroGnu** [comment]
My intention is that my script works as does "https://github.com/mrhydescripts/scripts/blob/master/starter.rb" if I'm not mistaken, look for the theme in "https://github.com/drjekyllthemes/themes/blob/master/themes.yml" and uses repo data

**Comment by geraldb** [comment]
> The reason to use the mr-hyde branch is the _config.yml file, include $name$ and $title$ to setup author: 

If you use Mr Hyde (NOT Qk/Quik) you do NOT need to use variables e.g. $name$ - just use defaults as usual and Mr Hyde will overwrite the props in the generated _yaml.

> p.s. the theme does not appear in "http://drjekyllthemes.github.io/"

It's online on the command line tool.
The "visual" site directory needs to get updated (it's a git submode and build script to push). Sorry. Will take some days.

**Comment by geraldb** [comment]
> if I'm not mistaken, look for the theme in "https://github.com/drjekyllthemes/themes/blob/master/themes.yml" and uses repo data

Sorry: You're right - mr hyde uses the key from dr jekyll -> https://github.com/mrhydescripts/mrhyde/blob/master/lib/mrhyde/builder.rb#L33  Should support both ways ;-) Will add it to the todo list.

**Comment by StartZeroGnu** [comment]
then I remove the branch "mr-hyde", and remove "branch" in "https://github.com/drjekyllthemes/themes/blob/master/themes.yml"

```
- title:     SZ-Flex (Blog)
  github:    StartZeroGnu/jekyll-szflex-theme
  demo_url:  http://startzerognu.neocities.org/sz-flex/
  author:    StartZeroGnu
  thumbnail: sz-flex.png
  license:   MIT
  tags:      [blog]
```

and I have to wait until you can fix the issue

Thanks!!!

**Comment by geraldb** [comment]
@StartZeroGnu  It's working **today**, that is, please use the drjekyll (generated) key for the install_theme call. If you wait for a fix (it might be a long wait - sorry - two weeks+).

**Comment by geraldb** [comment]
@StartZeroGnu  FYI: To make it easy I removed the branch entry in themes.yml (https://github.com/drjekyllthemes/themes/blob/master/themes.yml) for you just now. Cheers.

**Comment by StartZeroGnu** [comment]
> FYI: To make it easy I removed the branch entry in themes.yml 

thanks, I was trying to change and was no longer

>  If you wait for a fix (it might be a long wait - sorry - two weeks+).

ok, no problem, I wait

**Comment by geraldb** [comment]
@StartZeroGnu  FYI: Thanks for the two tickets on drjkeyll and mrhyde. It's fixed now. Update the drjekyll theme and than try:

```
$ mrhyde new sz-flex
```

It's now working (as advertised). Thanks for trying. Cheers.

**Comment by StartZeroGnu** [comment]
Thanks @geraldb that's very good news, I'll try it immediately!!!

**Comment by StartZeroGnu** [comment]
Works great, thanks @geraldb , you've done a great job.

**Comment by StartZeroGnu** [comment]
@geraldb Correct me if I'm wrong about (https://github.com/mrhydescripts/mrhyde/blob/master/lib/mrhyde/builder.rb#L33)

Using starter.rb as an example

`$ mrhyde new starter` call -> https://github.com/mrhydescripts/scripts/blob/master/starter.rb and `install_theme` (https://github.com/mrhydescripts/scripts/blob/master/starter.rb#L14) -> search in -> https://github.com/drjekyllthemes/themes/blob/master/themes.yml find "Starter" in "Title" https://github.com/drjekyllthemes/themes/blob/master/themes.yml#L21 and download theme ???

**Comment by geraldb** [comment]
@StartZeroGnu  Not sure if that's a question. But yes - that's how it works for now - mrhyde still looks up the theme in the (online) drjekyll themes.yml datafile. Cheers.
